repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.4.3
      hooks:
          # Run the linter.
          - id: ruff
            args:
                [--fix]
                # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.2
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py310-plus]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: check-json
          # Unsafe required for mkdocs.yml format
          - id: check-yaml
            args: [--unsafe]
          - id: check-toml
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            files: \.(md|yml)$
    - repo: https://github.com/datarootsio/databooks
      rev: 1.1.1
      hooks:
          - id: databooks-meta
            #   - repo: https://github.com/pycqa/pydocstyle
            #     rev: 6.1.1  # pick a git hash / tag to point to
            #     hooks:
            #       - id: pydocstyle
