repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
          - id: mixed-line-ending
          - id: name-tests-test
          - id: requirements-txt-fixer
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.12.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/psf/black
      rev: 24.1.1 # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+
          - id: black-jupyter
            language_version: python3 # Should be a command that runs python3.6+
#   - repo: https://github.com/pycqa/pydocstyle
#     rev: 6.1.1  # pick a git hash / tag to point to
#     hooks:
#       - id: pydocstyle
