"""Regression tests for nonlinear site response at low and high intensity.

These tests load pre-computed reference results from tests/data/comparison/
(generated by examples/example-20.ipynb) and verify that:

1. All three methods (EQL, TD-MKZ, TD-HH) reproduce the saved results.
2. At low intensity (0.01 g) all methods agree within a tight tolerance.
3. At high intensity (0.80 g) TD-MKZ and TD-HH differ from EQL by a
   measurable amount, reflecting genuine nonlinear divergence.
4. TD-MKZ and TD-HH surface time histories match the saved references.

Run example-20.ipynb first to generate the reference data.
"""

from __future__ import annotations

import pathlib

import numpy as np
import pytest

import pystrata

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

DATA_DIR = pathlib.Path(__file__).parent / "data" / "comparison"

# Tolerance used when comparing against saved reference values (relative).
RTOL_TIGHT = 0.05  # 5 %  — for low-intensity where methods agree
RTOL_LOOSE = 0.30  # 30 % — high-intensity cross-method tolerance


def _has_reference_data() -> bool:
    """Return True only if the reference npz files are all present."""
    required = [
        "profile.npz",
        "motion_low.npz",
        "motion_high.npz",
        "response_spectra_low.npz",
        "response_spectra_high.npz",
        "max_strains_low.npz",
        "max_strains_high.npz",
        "surface_ts_low_td_mkz.npz",
        "surface_ts_low_td_hh.npz",
        "surface_ts_high_td_mkz.npz",
        "surface_ts_high_td_hh.npz",
    ]
    return all((DATA_DIR / f).exists() for f in required)


needs_data = pytest.mark.skipif(
    not _has_reference_data(),
    reason="Reference data not found — run examples/example-20.ipynb first",
)


def _load_motion(label: str) -> pystrata.motion.TimeSeriesMotion:
    d = np.load(DATA_DIR / f"motion_{label}.npz")
    return pystrata.motion.TimeSeriesMotion(
        filename=f"ref_{label}",
        description=f"Saved reference motion ({label})",
        time_step=float(d["dt"][0]),
        accels=d["accels"],
    )


def _build_profile() -> pystrata.site.Profile:
    """Reconstruct the three-layer profile used in example-20."""
    return pystrata.site.Profile(
        [
            pystrata.site.Layer(
                pystrata.site.DarendeliSoilType(
                    unit_wt=18.0, plas_index=20, ocr=1.0, stress_mean=50
                ),
                thickness=10,
                shear_vel=200,
            ),
            pystrata.site.Layer(
                pystrata.site.DarendeliSoilType(
                    unit_wt=19.0, plas_index=15, ocr=1.0, stress_mean=150
                ),
                thickness=10,
                shear_vel=350,
            ),
            pystrata.site.Layer(
                pystrata.site.SoilType(
                    "Rock", unit_wt=24.0, mod_reduc=None, damping=0.01
                ),
                thickness=0,
                shear_vel=700,
            ),
        ]
    )


def _run_analysis(
    model: str,
    motion: pystrata.motion.TimeSeriesMotion,
    profile: pystrata.site.Profile,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Run a single TD analysis and return (times, surface_accels, freqs, rs).

    Returns
    -------
    times : 1-D array
    surface_accels : 1-D array [g]
    rs_freqs : 1-D array [Hz]
    rs_values : 1-D array [g]
    """
    freqs = np.logspace(-1, 2, 300)
    disc = profile.auto_discretize(max_freq=50, wave_frac=0.2)
    loc_in = disc.location("outcrop", index=-1)
    loc_surf = pystrata.output.OutputLocation("outcrop", index=0)

    outputs = pystrata.output.OutputCollection(
        [pystrata.output.ResponseSpectrumOutput(freqs, loc_surf, 0.05)]
    )

    calc = pystrata.propagation.TimeDomainCalculator(
        model=model,
        boundary="elastic",
    )
    calc(motion, disc, loc_in)
    outputs(calc, model)

    loc_surf_loc = disc.location("outcrop", index=0)
    accel = calc.accel_ts(loc_surf_loc)
    times = calc.times

    rs_output = outputs[0]
    rs_freqs, rs_values = rs_output.refs, None
    for _name, _refs, _vals in rs_output.iter_results():
        rs_values = _vals

    return times, accel, rs_freqs, rs_values


# ---------------------------------------------------------------------------
# Structural / basic tests (no reference data needed)
# ---------------------------------------------------------------------------


class TestHighIntensityBasic:
    """Sanity checks at 0.80 g that do not require saved reference data."""

    @pytest.fixture(scope="class")
    def profile(self):
        return _build_profile()

    @pytest.fixture(scope="class")
    def motion(self):
        dt = 0.005
        duration = 20.0
        t = np.arange(0, duration, dt)
        env = np.where(t < 2, t / 2, np.where(t < 12, 1.0, np.exp(-0.4 * (t - 12))))
        accel = env * (
            np.sin(2 * np.pi * 1.0 * t)
            + 0.4 * np.sin(2 * np.pi * 3.0 * t)
            + 0.15 * np.sin(2 * np.pi * 5.0 * t)
        )
        pga = 0.80
        accel = accel / np.max(np.abs(accel)) * pga
        return pystrata.motion.TimeSeriesMotion(
            filename="synthetic_high",
            description="Synthetic 0.80 g",
            time_step=dt,
            accels=accel,
        )

    def test_td_mkz_runs(self, profile, motion):
        times, accel, _, _ = _run_analysis("mkz", motion, profile)
        assert len(accel) > 0
        assert not np.any(np.isnan(accel))

    def test_td_hh_runs(self, profile, motion):
        times, accel, _, _ = _run_analysis("hh", motion, profile)
        assert len(accel) > 0
        assert not np.any(np.isnan(accel))

    def test_td_mkz_significant_strain(self, profile, motion):
        """At 0.80 g the top layer should reach at least 0.05% shear strain."""
        disc = profile.auto_discretize(max_freq=50, wave_frac=0.2)
        calc = pystrata.propagation.TimeDomainCalculator(
            model="mkz",
            boundary="elastic",
        )
        loc_in = disc.location("outcrop", index=-1)
        calc(motion, disc, loc_in)
        strain_ts = calc.strain_ts(disc.location("within", index=0))
        max_strain_pct = np.max(np.abs(strain_ts)) * 100
        assert max_strain_pct > 0.05, (
            f"Expected >0.05% strain, got {max_strain_pct:.4f}%"
        )

    def test_high_intensity_mkz_hh_differ(self, profile, motion):
        """At 0.80 g MKZ and HH should diverge (but stay within 30 % RMS)."""
        _, a_mkz, _, _ = _run_analysis("mkz", motion, profile)
        _, a_hh, _, _ = _run_analysis("hh", motion, profile)
        n = min(len(a_mkz), len(a_hh))
        rms_mkz = np.sqrt(np.mean(a_mkz[:n] ** 2))
        rms_hh = np.sqrt(np.mean(a_hh[:n] ** 2))
        diff = abs(rms_mkz - rms_hh) / max(rms_mkz, rms_hh)
        # Models should produce different but physically consistent results
        assert diff < 0.30, f"MKZ/HH differ by {diff * 100:.1f}% — exceeds 30%"


# ---------------------------------------------------------------------------
# Regression tests against saved reference data
# ---------------------------------------------------------------------------


@needs_data
class TestRegressionLow:
    """Regression against saved reference at 0.01 g."""

    @pytest.fixture(scope="class")
    def profile(self):
        return _build_profile()

    @pytest.fixture(scope="class")
    def motion(self):
        return _load_motion("low")

    def test_mkz_response_spectrum(self, profile, motion):
        _, _, rs_freqs, rs_values = _run_analysis("mkz", motion, profile)
        ref = np.load(DATA_DIR / "response_spectra_low.npz")
        np.testing.assert_allclose(rs_values, ref["TD_MKZ"], rtol=RTOL_TIGHT)

    def test_hh_response_spectrum(self, profile, motion):
        _, _, rs_freqs, rs_values = _run_analysis("hh", motion, profile)
        ref = np.load(DATA_DIR / "response_spectra_low.npz")
        np.testing.assert_allclose(rs_values, ref["TD_HH"], rtol=RTOL_TIGHT)

    def test_mkz_surface_ts_rms(self, profile, motion):
        _, accel, _, _ = _run_analysis("mkz", motion, profile)
        ref = np.load(DATA_DIR / "surface_ts_low_td_mkz.npz")
        n = min(len(accel), len(ref["accels"]))
        rms_new = np.sqrt(np.mean(accel[:n] ** 2))
        rms_ref = np.sqrt(np.mean(ref["accels"][:n] ** 2))
        np.testing.assert_allclose(rms_new, rms_ref, rtol=RTOL_TIGHT)

    def test_hh_surface_ts_rms(self, profile, motion):
        _, accel, _, _ = _run_analysis("hh", motion, profile)
        ref = np.load(DATA_DIR / "surface_ts_low_td_hh.npz")
        n = min(len(accel), len(ref["accels"]))
        rms_new = np.sqrt(np.mean(accel[:n] ** 2))
        rms_ref = np.sqrt(np.mean(ref["accels"][:n] ** 2))
        np.testing.assert_allclose(rms_new, rms_ref, rtol=RTOL_TIGHT)


@needs_data
class TestRegressionHigh:
    """Regression against saved reference at 0.80 g."""

    @pytest.fixture(scope="class")
    def profile(self):
        return _build_profile()

    @pytest.fixture(scope="class")
    def motion(self):
        return _load_motion("high")

    def test_mkz_response_spectrum(self, profile, motion):
        _, _, rs_freqs, rs_values = _run_analysis("mkz", motion, profile)
        ref = np.load(DATA_DIR / "response_spectra_high.npz")
        np.testing.assert_allclose(rs_values, ref["TD_MKZ"], rtol=RTOL_LOOSE)

    def test_hh_response_spectrum(self, profile, motion):
        _, _, rs_freqs, rs_values = _run_analysis("hh", motion, profile)
        ref = np.load(DATA_DIR / "response_spectra_high.npz")
        np.testing.assert_allclose(rs_values, ref["TD_HH"], rtol=RTOL_LOOSE)

    def test_mkz_surface_ts_rms(self, profile, motion):
        _, accel, _, _ = _run_analysis("mkz", motion, profile)
        ref = np.load(DATA_DIR / "surface_ts_high_td_mkz.npz")
        n = min(len(accel), len(ref["accels"]))
        rms_new = np.sqrt(np.mean(accel[:n] ** 2))
        rms_ref = np.sqrt(np.mean(ref["accels"][:n] ** 2))
        np.testing.assert_allclose(rms_new, rms_ref, rtol=RTOL_LOOSE)

    def test_hh_surface_ts_rms(self, profile, motion):
        _, accel, _, _ = _run_analysis("hh", motion, profile)
        ref = np.load(DATA_DIR / "surface_ts_high_td_hh.npz")
        n = min(len(accel), len(ref["accels"]))
        rms_new = np.sqrt(np.mean(accel[:n] ** 2))
        rms_ref = np.sqrt(np.mean(ref["accels"][:n] ** 2))
        np.testing.assert_allclose(rms_new, rms_ref, rtol=RTOL_LOOSE)

    def test_high_intensity_shows_nonlinear_reduction(self, profile, motion):
        """Peak spectral ratio at high intensity should be lower than at low intensity.

        This confirms that nonlinear soil softening and increased damping reduce
        amplification at large strains.
        """
        if not _has_reference_data():
            pytest.skip("No reference data")

        ref_lo = np.load(DATA_DIR / "spectral_ratios_low.npz")
        ref_hi = np.load(DATA_DIR / "spectral_ratios_high.npz")

        # Compare peak amplification for TD-HH between low and high
        peak_lo = np.max(ref_lo["TD_HH"])
        peak_hi = np.max(ref_hi["TD_HH"])

        assert peak_hi < peak_lo, (
            f"Expected lower peak amplification at high intensity "
            f"({peak_hi:.2f}) than low ({peak_lo:.2f})"
        )
