#!/usr/bin/env python
#
# pyStrata documentation build configuration file, created by
# sphinx-quickstart on Mon Nov  2 15:41:52 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# Add the source directory to the Python path
sys.path.insert(0, os.path.abspath('../src'))

try:
    import pystrata
except ImportError:
    # Fallback values if pystrata cannot be imported
    class MockPystrata:
        __title__ = "PyStrata"
        __copyright__ = "2024, Albert Kottke"
        __author__ = "Albert Kottke"
        __version__ = "0.5.5"

    pystrata = MockPystrata()

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

extensions = [
    "nbsphinx",
    "nbsphinx_link",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
    "sphinx_design",
]

# Minimal extension config
autodoc_member_order = "bysource"
autosummary_generate = True
numpydoc_show_class_members = False
bibtex_bibfiles = ["refs.bib"]

# Templates and static paths
templates_path = ["_templates"]
exclude_patterns = ["_build", "_templates"]

# Project info
project = pystrata.__title__
copyright = pystrata.__copyright__
author = pystrata.__author__
version = pystrata.__version__
release = version

# HTML theme
html_theme = "furo"
html_static_path = ['_static']
html_css_files = ['custom.css']

# NBSphinx config
nbsphinx_execute = 'never'
nbsphinx_allow_errors = True
nbsphinx_timeout = 300

# Bibtex config
bibtex_reference_style = 'author_year'
bibtex_default_style = 'plain'

# Napoleon config
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_param = True
napoleon_use_rtype = True
