name: GitHub Actions Version Updater

# Controls when the action will run.
on:
    workflow_dispatch:

    schedule:
        # Automatically run on every Sunday
        - cron: "0 0 * * 0"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7
              with:
                  # [Required] Access token with `workflow` scope.
                  token: ${{ secrets.UPDATER_TOKEN }}

            - name: Remove LFS hooks
              # This repository uses Git LFS, but it not being
              # in the container causes the action to fail to create a new branch.
              # Removing the hooks manually is harmless and works around this issue.
              run: |
                  rm .git/hooks/post-checkout
                  rm .git/hooks/pre-push

            - name: Run GitHub Actions Version Updater
              uses: saadmk11/github-actions-version-updater@v0.8.1
              with:
                  # [Required] Access token with `workflow` scope.
                  token: ${{ secrets.UPDATER_TOKEN }}
